// MView6 -- High-performance PDF and photo viewer built with Rust and GTK4
//
// Copyright (c) 2024-2025 Martin van der Werff <github (at) newinnovations.nl>
//
// This file is part of MView6.
//
// MView6 is free software: you can redistribute it and/or modify it under the terms of
// the GNU Affero General Public License as published by the Free Software Foundation, either
// version 3 of the License, or (at your option) any later version.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
// BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// **DO NOT EDIT** This file is generated by tools/create_colors.py

#![allow(dead_code)]

use cairo::Context;

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Color {
    White,            // #ffffff
    Black,            // #000000
    Red,              // #ff0000
    BlackBean,        // #331a1a
    Gray,             // #808080
    Silver,           // #cccccc
    RussianViolet,    // #330033
    Citrine,          // #e6cc33
    FolderBack,       // #1e3319
    FolderTitle,      // #94bc8a
    FolderMsg,        // #c0cebf
    ArchiveBack,      // #23213c
    ArchiveTitle,     // #89a6d2
    ArchiveMsg,       // #c3ccd9
    UnsupportedBack,  // #292500
    UnsupportedTitle, // #c4b850
    UnsupportedMsg,   // #d0cc9f
    ErrorBack,        // #372020
    ErrorTitle,       // #b38888
    ErrorMsg,         // #dbb5b5
}

impl Color {
    pub fn to_mview(self) -> MViewColor {
        match self {
            Self::White => WHITE,
            Self::Black => BLACK,
            Self::Red => RED,
            Self::BlackBean => BLACK_BEAN,
            Self::Gray => GRAY,
            Self::Silver => SILVER,
            Self::RussianViolet => RUSSIAN_VIOLET,
            Self::Citrine => CITRINE,
            Self::FolderBack => FOLDER_BACK,
            Self::FolderTitle => FOLDER_TITLE,
            Self::FolderMsg => FOLDER_MSG,
            Self::ArchiveBack => ARCHIVE_BACK,
            Self::ArchiveTitle => ARCHIVE_TITLE,
            Self::ArchiveMsg => ARCHIVE_MSG,
            Self::UnsupportedBack => UNSUPPORTED_BACK,
            Self::UnsupportedTitle => UNSUPPORTED_TITLE,
            Self::UnsupportedMsg => UNSUPPORTED_MSG,
            Self::ErrorBack => ERROR_BACK,
            Self::ErrorTitle => ERROR_TITLE,
            Self::ErrorMsg => ERROR_MSG,
        }
    }

    pub fn to_hex(self) -> String {
        self.to_mview().to_hex()
    }
}

pub trait CairoColorExt {
    fn color(&self, color: Color);
}

impl CairoColorExt for Context {
    fn color(&self, color: Color) {
        let c = color.to_mview();
        self.set_source_rgb(c.r as f64 / 255.0, c.g as f64 / 255.0, c.b as f64 / 255.0);
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct MViewColor {
    r: u8,
    g: u8,
    b: u8,
}

impl MViewColor {
    pub fn to_hex(self) -> String {
        format!("#{:02X}{:02X}{:02X}", self.r, self.g, self.b)
    }
}

const WHITE: MViewColor = MViewColor {
    r: 0xff,
    g: 0xff,
    b: 0xff,
};
const BLACK: MViewColor = MViewColor {
    r: 0x00,
    g: 0x00,
    b: 0x00,
};
const RED: MViewColor = MViewColor {
    r: 0xff,
    g: 0x00,
    b: 0x00,
};
const BLACK_BEAN: MViewColor = MViewColor {
    r: 0x33,
    g: 0x1a,
    b: 0x1a,
};
const GRAY: MViewColor = MViewColor {
    r: 0x80,
    g: 0x80,
    b: 0x80,
};
const SILVER: MViewColor = MViewColor {
    r: 0xcc,
    g: 0xcc,
    b: 0xcc,
};
const RUSSIAN_VIOLET: MViewColor = MViewColor {
    r: 0x33,
    g: 0x00,
    b: 0x33,
};
const CITRINE: MViewColor = MViewColor {
    r: 0xe6,
    g: 0xcc,
    b: 0x33,
};
const FOLDER_BACK: MViewColor = MViewColor {
    r: 0x1e,
    g: 0x33,
    b: 0x19,
};
const FOLDER_TITLE: MViewColor = MViewColor {
    r: 0x94,
    g: 0xbc,
    b: 0x8a,
};
const FOLDER_MSG: MViewColor = MViewColor {
    r: 0xc0,
    g: 0xce,
    b: 0xbf,
};
const ARCHIVE_BACK: MViewColor = MViewColor {
    r: 0x23,
    g: 0x21,
    b: 0x3c,
};
const ARCHIVE_TITLE: MViewColor = MViewColor {
    r: 0x89,
    g: 0xa6,
    b: 0xd2,
};
const ARCHIVE_MSG: MViewColor = MViewColor {
    r: 0xc3,
    g: 0xcc,
    b: 0xd9,
};
const UNSUPPORTED_BACK: MViewColor = MViewColor {
    r: 0x29,
    g: 0x25,
    b: 0x00,
};
const UNSUPPORTED_TITLE: MViewColor = MViewColor {
    r: 0xc4,
    g: 0xb8,
    b: 0x50,
};
const UNSUPPORTED_MSG: MViewColor = MViewColor {
    r: 0xd0,
    g: 0xcc,
    b: 0x9f,
};
const ERROR_BACK: MViewColor = MViewColor {
    r: 0x37,
    g: 0x20,
    b: 0x20,
};
const ERROR_TITLE: MViewColor = MViewColor {
    r: 0xb3,
    g: 0x88,
    b: 0x88,
};
const ERROR_MSG: MViewColor = MViewColor {
    r: 0xdb,
    g: 0xb5,
    b: 0xb5,
};
