[package]
name = "MView6"
version = "6.0.0-dev"
edition = "2021"
authors = ["Martin van der Werff <github@newinnovations.nl>"]
description = "High-performance PDF and photo viewer built with Rust and GTK4"
repository = "https://github.com/newinnovations/mview6"
license = "AGPL"

[package.metadata.winresource]
LegalCopyright = "Copyright © 2024-2026 Martin van der Werff"

[dependencies]
async-channel = "2.3.1"
base64 = "0.23.1"
cairo-rs = { version = "0.22", features = ["v1_18", "png"] }
chrono = "0.4.38"
clap = { version = "4.6", features = ["derive"] }
convert_case = "0.12.0"
dirs = "7.0.0"
gdk-pixbuf = { version = "0.22", features = ["v2_42"] }
gio = { version = "0.22", features = ["v2_80"] }
glib = { version = "0.22", features = ["v2_80"] }
gtk4 = { version = "0.11", features = ["v4_14"] }
human_bytes = { version = "0.4.3", features = ["fast"], default-features = false }
image = { version = "0.25.6", features = ["avif-native"] }
image-webp = "0.2.1"
kamadak-exif = "0.6.1"
mupdf = { git = "https://github.com/messense/mupdf-rs.git", features = ["sys-lib-libjpeg"], optional = true}
pdfium = "0.10"
regex = "1.10.4"
resvg = { git = "https://github.com/newinnovations/resvg", branch = "flatten-cached" }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
sha2 = "0.11.0"
unrar = "0.5.3"
zip = "8.6.0"
syntect = "5.2.0"

[build-dependencies]
glib-build-tools = "0.22"
winresource = "0.1"

[features]
default = ["mupdf"]
mupdf = ["dep:mupdf"]
